server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://USER-SERVICE
          #url: http://localhost:9093
          predicates:
            - Path=/songsWS-Moroz_KBE/auth/**
        - id: songsWS
          uri: http://songsWS
          #uri: http://localhost:9091
          predicates:
            - Path=/songsWS-Moroz_KBE/songs/**
        - id: nosql-server
          uri: lb://nosql-server
          #uri: http://localhost:9095
          predicates:
            - Path=/songsWS-Moroz_KBE/nosql/**



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost