server:
  port: 9091

spring:
  application:
    name: songsWS

spring.jpa.properties.hibernate.physical_naming_strategy:
  org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

